# Module V - Assignment

You can complete this by yourself or with 1-2 other people. List all names at the top of the module when you submit.

The initial data for this assignment came from UCI's Machine Learning Repository, though has been modified and loosely framed around a client inquiry that LionBase processed in the past.

## Problem

Recall the Module II Assignment --

EnviroBox is a company in North Africa that has developed a modular and affordable greenhouse for farmers hit hard by climate change. Their business model works as follows:
- Provide loans to farmers to finance the greenhouse
- The farmer eventually pays back EnviroBox with interest through the crop earnings

If an individual receives a loan and ends being unable to pay it back, EnviroBox loses \$5,000 on average.

If an individual receives a loan and ends up being able to pay it back, EnviroBox earns \$5,000 on average.

EnviroBox would like to engage in a marketing campaign to get people to take their loans. The goal is to predict whether or not someone will take the farm loan.

enviro-box.csv contains the following data fields:
- age
- job
- marital 
- education
- default (has credit in default?)
- balance (amount of money they currently have)
- housing (whether they currently have a housing loan in the past)
- personal_loan (whether they currently have an existing personal loan not from EnviroBox)
- contact (how they were contacted)
- day (day of the week, in numbers)
- month
- duration (last contact duration, in seconds)
- campaign (# of contacts performed during this campaign and for this client)
- pdays (# of days that passed by after client was last contacted from previous campaign)
- poutcome (outcome of previous marketing campaign)
- y (whether or not the client has taken a loan from EnviroBox) -- **this is the dependent variable we are predicting**

Here, you went through model selection and assessment.

Write up a report that includes, at minimum:
- Your selected model
- Two different visualizations that drive an actionable insight

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("data/enviro-box.csv", index_col = 0)

In [6]:
df.head()

,age,job,marital,education,default,balance,housing,personal_loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,rancher,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,largeholder farmer,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,smallholder farmer,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no